Updated `bin/setup` file

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -3,6 +3,18 @@ set -euo pipefail
 IFS=$'\n\t'
 set -vx
 
+PROJECT_NAME='genius-api'
+if pwd | grep $PROJECT_NAME; then
+  cd "${PWD%$PROJECT_NAME*}$PROJECT_NAME"
+else
+  echo "Change your working directory to the $PROJECT_NAME dir or its relative directories. Exiting with error code 1"
+  exit 1
+fi
+
 bundle install
 
-# Do any other automated setup that you need to do here
+gem build "$PROJECT_NAME".gemspec
+GEM_VERSION=$(bundle info $PROJECT_NAME | head -n 1 | sed 's/.*(\(.*\))/\1/')
+GEM_ARCHIVE="$PROJECT_NAME-$GEM_VERSION.gem"
+gem install "$GEM_ARCHIVE"
+bin/console
